// <auto-generated />
using System;
using ExamArchive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamArchive.Migrations
{
    [DbContext(typeof(ExamArchiveDbContext))]
    [Migration("20260917151932_RemoveClaimTokenHash")]
    partial class RemoveClaimTokenHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StudiesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudiesId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("ExamArchive.Models.MajorSubject", b =>
                {
                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("MajorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("MajorSubjects", t =>
                        {
                            t.HasCheckConstraint("CK_MajorSubject_YearOfStudy", "`YearOfStudy` >= 1 AND `YearOfStudy` <= 6");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("SubjectId", "Year", "Month");

                    b.ToTable("Papers", t =>
                        {
                            t.HasCheckConstraint("CK_Paper_ExamType", "`ExamType` IN ('Midterm', 'Final', 'Resit')");

                            t.HasCheckConstraint("CK_Paper_Month", "`Month` >= 1 AND `Month` <= 12");

                            t.HasCheckConstraint("CK_Paper_RejectionReason", "`Status` = 'Rejected' OR `RejectionReason` IS NULL");

                            t.HasCheckConstraint("CK_Paper_ReviewedAt", "`Status` <> 'Pending' OR `ReviewedAt` IS NULL");

                            t.HasCheckConstraint("CK_Paper_Status", "`Status` IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.PaperFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PaperId", "PageNumber")
                        .IsUnique();

                    b.ToTable("PaperFiles", t =>
                        {
                            t.HasCheckConstraint("CK_PaperFile_ContentType", "`ContentType` IN ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')");

                            t.HasCheckConstraint("CK_PaperFile_PageNumber", "`PageNumber` >= 1");

                            t.HasCheckConstraint("CK_PaperFile_SizeBytes", "`SizeBytes` >= 0");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Studies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Studies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "Bachelor's",
                            NameSr = "Основне академске студије"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Master's",
                            NameSr = "Мастер академске студије"
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ExamArchive.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "`Role` IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.HasOne("ExamArchive.Models.Studies", "Studies")
                        .WithMany("Majors")
                        .HasForeignKey("StudiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("ExamArchive.Models.MajorSubject", b =>
                {
                    b.HasOne("ExamArchive.Models.Major", "Major")
                        .WithMany("MajorSubjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamArchive.Models.Subject", "Subject")
                        .WithMany("MajorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.HasOne("ExamArchive.Models.Subject", "Subject")
                        .WithMany("Papers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamArchive.Models.User", "SubmittedBy")
                        .WithMany("Papers")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subject");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("ExamArchive.Models.PaperFile", b =>
                {
                    b.HasOne("ExamArchive.Models.Paper", "Paper")
                        .WithMany("Files")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.Navigation("MajorSubjects");
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ExamArchive.Models.Studies", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("ExamArchive.Models.Subject", b =>
                {
                    b.Navigation("MajorSubjects");

                    b.Navigation("Papers");
                });

            modelBuilder.Entity("ExamArchive.Models.User", b =>
                {
                    b.Navigation("Papers");
                });
#pragma warning restore 612, 618
        }
    }
}
